#!/bin/sh

if grep -q '^deb ' /target/etc/apt/sources.list; then
    echo "INFO: sources.list is configured, everything is fine"
    exit 0
fi

echo "INFO: sources.list is empty, setting up a default one for Kali"

cat >/target/etc/apt/sources.list <<END
# See https://www.kali.org/docs/general-use/kali-linux-sources-list-repositories/
deb http://http.kali.org/kali kali-rolling main contrib non-free

# Additional line for source packages
# deb-src http://http.kali.org/kali kali-rolling main contrib non-free
END
in-target apt-get update || true
